openapi: 3.0.0
info:
  title: Express/Node Swagger Sample
  description: '**MEN Stack**'
  contact: {}
  version: '1.0'
servers:
  - url: http://localhost:5000
    variables: {}
paths:
  /api/courses:
    get:
      tags:
        - Courses
      summary: Get all courses
      operationId: GetCourses
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  # /users/{id}:
  #   parameters:
  #     - in: path
  #       name: id
  #       schema:
  #         type: string
  #       required: true
  #       description: The user ID
  #   get:
  #     tags:
  #       - Auth
  #     summary: Get User
  #     operationId: GetUser
  #     parameters: []
  #     responses:
  #       '200':
  #         description: ''
  #         headers: {}
  #     deprecated: false
components:
  schemas:
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
